/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author GINO
 */
public class Panel extends javax.swing.JFrame {

    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        getDNIUsuario = new javax.swing.JLabel();
        getTablaPrincipal = new javax.swing.JTabbedPane();
        IntroPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PanelOrden = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        getBtnOrdenIDProducto = new javax.swing.JButton();
        getOrdenProductoID = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        getOrdenNombreProducto = new javax.swing.JLabel();
        getOrdenPrecioProducto = new javax.swing.JLabel();
        getOrdenStockProducto = new javax.swing.JLabel();
        getOrdenCantidad = new javax.swing.JSpinner();
        getOrdenAgregarPedido = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        getTablaOrden = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        getBtnOrdenNombreCliente = new javax.swing.JButton();
        getOrdenNombreCliente = new javax.swing.JLabel();
        getOrdenDniCliente = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        getBtnOrdenImprimir = new javax.swing.JButton();
        PanelCliente = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        getClienteNombreApellido = new javax.swing.JTextField();
        getClienteCorreo = new javax.swing.JTextField();
        getClienteCelular = new javax.swing.JTextField();
        getClienteDireccion = new javax.swing.JTextField();
        getBtnClienteAgregar = new javax.swing.JButton();
        getBtnClienteBorrar = new javax.swing.JButton();
        getBtnClienteNuevo = new javax.swing.JButton();
        getBtnClienteModificar = new javax.swing.JButton();
        getClienteDNI = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        getTablaCliente = new javax.swing.JTable();
        PanelProducto = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        getProductoID = new javax.swing.JLabel();
        getProductoNombre = new javax.swing.JTextField();
        getProductoPrecio = new javax.swing.JTextField();
        getBtnProductoAgregar = new javax.swing.JButton();
        getBtnProductoBorrar = new javax.swing.JButton();
        getBtnProductoNuevo = new javax.swing.JButton();
        getBtnProductoModificar = new javax.swing.JButton();
        getProductoListaCategoria = new javax.swing.JComboBox<>();
        getProductoStock = new javax.swing.JSpinner();
        jScrollPane4 = new javax.swing.JScrollPane();
        getTablaProducto = new javax.swing.JTable();
        PanelDetalleOrden = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        getBtnDetalleOrdenIDOrden = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        getTablaDetalleOrden = new javax.swing.JTable();
        getDetalleOrdenNombreCompleto_cliente = new javax.swing.JLabel();
        getDetalleOrdenDNI_cliente = new javax.swing.JLabel();
        getBtnDetalleOrdenImprimir = new javax.swing.JButton();
        PanelCategoria = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        getCategoriaID = new javax.swing.JLabel();
        getCategoriaNombre = new javax.swing.JTextField();
        getBtnCategoriaAgregar = new javax.swing.JButton();
        getBtnCategoriaBorrar = new javax.swing.JButton();
        getBtnCategoriaModificar = new javax.swing.JButton();
        getBtnCategoriaNuevo = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        getTablaCategoria = new javax.swing.JTable();
        PanelUsuario = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        getUsuarioNombreApellido = new javax.swing.JTextField();
        getUsuarioCorreo = new javax.swing.JTextField();
        getUsuarioUsername = new javax.swing.JTextField();
        getUsuarioPassword = new javax.swing.JTextField();
        getBtnUsuarioAgregar = new javax.swing.JButton();
        getBtnUsuarioBorrar = new javax.swing.JButton();
        getBtnUsuarioNuevo = new javax.swing.JButton();
        getBtnUsuarioModificar = new javax.swing.JButton();
        getUsuarioDNI = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        getTablaUsuario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        getBtnOrden = new javax.swing.JButton();
        getBtnClientes = new javax.swing.JButton();
        getBtnProductos = new javax.swing.JButton();
        getBtnDetalleOrden = new javax.swing.JButton();
        getBtnCategorias = new javax.swing.JButton();
        getBtnUsuarios = new javax.swing.JButton();
        getBtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));

        jPanel11.setBackground(new java.awt.Color(255, 153, 51));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(255, 153, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DNI USUARIO:");

        getDNIUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getDNIUsuario.setForeground(new java.awt.Color(255, 255, 255));
        getDNIUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getDNIUsuario.setText("78965412");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(getDNIUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(519, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getDNIUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 110));

        getTablaPrincipal.setEnabled(false);

        IntroPanel.setBackground(new java.awt.Color(255, 153, 51));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/buscar_producto_40pxls.png"))); // NOI18N

        javax.swing.GroupLayout IntroPanelLayout = new javax.swing.GroupLayout(IntroPanel);
        IntroPanel.setLayout(IntroPanelLayout);
        IntroPanelLayout.setHorizontalGroup(
            IntroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IntroPanelLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        IntroPanelLayout.setVerticalGroup(
            IntroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IntroPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getTablaPrincipal.addTab("tab7", IntroPanel);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("ID Producto"));

        getBtnOrdenIDProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/buscar_producto_40pxls.png"))); // NOI18N
        getBtnOrdenIDProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        getOrdenProductoID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getOrdenProductoID.setForeground(new java.awt.Color(153, 153, 153));
        getOrdenProductoID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getOrdenProductoID.setText("ORD00001");
        getOrdenProductoID.setToolTipText("");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(getBtnOrdenIDProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(getOrdenProductoID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(getBtnOrdenIDProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(getOrdenProductoID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripcion Producto"));

        getOrdenNombreProducto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getOrdenNombreProducto.setForeground(new java.awt.Color(0, 51, 255));
        getOrdenNombreProducto.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));

        getOrdenPrecioProducto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getOrdenPrecioProducto.setForeground(new java.awt.Color(0, 51, 255));
        getOrdenPrecioProducto.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio"));

        getOrdenStockProducto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getOrdenStockProducto.setForeground(new java.awt.Color(0, 51, 255));
        getOrdenStockProducto.setBorder(javax.swing.BorderFactory.createTitledBorder("Stock"));

        getOrdenCantidad.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        getOrdenAgregarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/agregar_40pxls.png"))); // NOI18N
        getOrdenAgregarPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(getOrdenStockProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getOrdenPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(getOrdenAgregarPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(getOrdenCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(getOrdenNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(getOrdenNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(getOrdenPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(getOrdenStockProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(getOrdenAgregarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(getOrdenCantidad))
                .addContainerGap())
        );

        getTablaOrden.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(getTablaOrden);

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        getBtnOrdenNombreCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/buscar_cliente_40pxls.png"))); // NOI18N
        getBtnOrdenNombreCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        getOrdenNombreCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getOrdenNombreCliente.setForeground(new java.awt.Color(153, 153, 153));
        getOrdenNombreCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getOrdenNombreCliente.setText("NOMBRES Y APELLIDOS");

        getOrdenDniCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getOrdenDniCliente.setForeground(new java.awt.Color(153, 153, 153));
        getOrdenDniCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getOrdenDniCliente.setText("DNI");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(getBtnOrdenNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(getOrdenNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(getOrdenDniCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(368, 368, 368))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(getBtnOrdenNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(getOrdenDniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getOrdenNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Imprimir Pedido"));

        getBtnOrdenImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/impresora 40pxl.png"))); // NOI18N
        getBtnOrdenImprimir.setText("Imprimir");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(getBtnOrdenImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(getBtnOrdenImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelOrdenLayout = new javax.swing.GroupLayout(PanelOrden);
        PanelOrden.setLayout(PanelOrdenLayout);
        PanelOrdenLayout.setHorizontalGroup(
            PanelOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOrdenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(PanelOrdenLayout.createSequentialGroup()
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelOrdenLayout.setVerticalGroup(
            PanelOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOrdenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelOrdenLayout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelOrdenLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        getTablaPrincipal.addTab("Orden", PanelOrden);

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        getClienteNombreApellido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getClienteNombreApellido.setForeground(new java.awt.Color(153, 153, 153));
        getClienteNombreApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getClienteNombreApellido.setText("NOMBRES Y APELLIDOS");

        getClienteCorreo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getClienteCorreo.setForeground(new java.awt.Color(153, 153, 153));
        getClienteCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getClienteCorreo.setText("CORREO");
        getClienteCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getClienteCorreoActionPerformed(evt);
            }
        });

        getClienteCelular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getClienteCelular.setForeground(new java.awt.Color(153, 153, 153));
        getClienteCelular.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getClienteCelular.setText("CELULAR");

        getClienteDireccion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getClienteDireccion.setForeground(new java.awt.Color(153, 153, 153));
        getClienteDireccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getClienteDireccion.setText("DIRECCION");

        getBtnClienteAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/agregar_40pxls.png"))); // NOI18N
        getBtnClienteAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        getBtnClienteBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/equiz_40pxl.png"))); // NOI18N
        getBtnClienteBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        getBtnClienteNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevo_40pxls.png"))); // NOI18N
        getBtnClienteNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        getBtnClienteModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/modificar_40pxls.png"))); // NOI18N
        getBtnClienteModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        getClienteDNI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getClienteDNI.setForeground(new java.awt.Color(153, 153, 153));
        getClienteDNI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getClienteDNI.setText("DNI");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(getClienteNombreApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(getClienteCorreo)
                    .addComponent(getClienteCelular)
                    .addComponent(getClienteDireccion)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(getBtnClienteNuevo)
                        .addGap(23, 23, 23)
                        .addComponent(getBtnClienteModificar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addComponent(getBtnClienteAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(getBtnClienteBorrar))
                    .addComponent(getClienteDNI))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(getClienteDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(getClienteNombreApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(getClienteCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(getClienteCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(getClienteDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(getBtnClienteBorrar)
                    .addComponent(getBtnClienteAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(getBtnClienteModificar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(getBtnClienteNuevo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        getTablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(getTablaCliente);

        javax.swing.GroupLayout PanelClienteLayout = new javax.swing.GroupLayout(PanelCliente);
        PanelCliente.setLayout(PanelClienteLayout);
        PanelClienteLayout.setHorizontalGroup(
            PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelClienteLayout.setVerticalGroup(
            PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClienteLayout.createSequentialGroup()
                .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelClienteLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelClienteLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );

        getTablaPrincipal.addTab("Clientes", PanelCliente);

        PanelProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder("Producto"));

        getProductoID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getProductoID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getProductoID.setText("P00000000");

        getProductoNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getProductoNombre.setForeground(new java.awt.Color(153, 153, 153));
        getProductoNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getProductoNombre.setText("NOMBRE");
        getProductoNombre.setToolTipText("");

        getProductoPrecio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getProductoPrecio.setForeground(new java.awt.Color(153, 153, 153));
        getProductoPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getProductoPrecio.setText("PRECIO");

        getBtnProductoAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/agregar_40pxls.png"))); // NOI18N

        getBtnProductoBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/equiz_40pxl.png"))); // NOI18N

        getBtnProductoNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevo_40pxls.png"))); // NOI18N
        getBtnProductoNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        getBtnProductoModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/modificar_40pxls.png"))); // NOI18N
        getBtnProductoModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        getProductoListaCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        getProductoStock.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(getProductoID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(getProductoNombre)
                    .addComponent(getProductoPrecio)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(getBtnProductoNuevo)
                        .addGap(23, 23, 23)
                        .addComponent(getBtnProductoModificar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                        .addComponent(getBtnProductoAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(getBtnProductoBorrar))
                    .addComponent(getProductoListaCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(getProductoStock))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(getProductoID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(getProductoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(getProductoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(getProductoStock, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(getProductoListaCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(getBtnProductoBorrar)
                    .addComponent(getBtnProductoAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(getBtnProductoModificar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(getBtnProductoNuevo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(17, 17, 17))
        );

        jScrollPane4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        getTablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(getTablaProducto);

        javax.swing.GroupLayout PanelProductoLayout = new javax.swing.GroupLayout(PanelProducto);
        PanelProducto.setLayout(PanelProductoLayout);
        PanelProductoLayout.setHorizontalGroup(
            PanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelProductoLayout.setVerticalGroup(
            PanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProductoLayout.createSequentialGroup()
                .addGroup(PanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelProductoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelProductoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane4)))
                .addContainerGap())
        );

        getTablaPrincipal.addTab("Productos", PanelProducto);

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("ORDENES DEL CLIENTE"));

        getBtnDetalleOrdenIDOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/MUNDO_PELUDO_40PXL.png"))); // NOI18N

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(getBtnDetalleOrdenIDOrden)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(getBtnDetalleOrdenIDOrden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        getTablaDetalleOrden.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(getTablaDetalleOrden);

        getDetalleOrdenNombreCompleto_cliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getDetalleOrdenNombreCompleto_cliente.setForeground(new java.awt.Color(153, 153, 153));
        getDetalleOrdenNombreCompleto_cliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getDetalleOrdenNombreCompleto_cliente.setText("NOMBRE Y APELLIDO");

        getDetalleOrdenDNI_cliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getDetalleOrdenDNI_cliente.setForeground(new java.awt.Color(153, 153, 153));
        getDetalleOrdenDNI_cliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getDetalleOrdenDNI_cliente.setText("DNI");

        getBtnDetalleOrdenImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/impresora 40pxl.png"))); // NOI18N
        getBtnDetalleOrdenImprimir.setText("Imprimir");

        javax.swing.GroupLayout PanelDetalleOrdenLayout = new javax.swing.GroupLayout(PanelDetalleOrden);
        PanelDetalleOrden.setLayout(PanelDetalleOrdenLayout);
        PanelDetalleOrdenLayout.setHorizontalGroup(
            PanelDetalleOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDetalleOrdenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDetalleOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDetalleOrdenLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(PanelDetalleOrdenLayout.createSequentialGroup()
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addGroup(PanelDetalleOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(getDetalleOrdenNombreCompleto_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(getDetalleOrdenDNI_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(getBtnDetalleOrdenImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        PanelDetalleOrdenLayout.setVerticalGroup(
            PanelDetalleOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDetalleOrdenLayout.createSequentialGroup()
                .addGroup(PanelDetalleOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDetalleOrdenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelDetalleOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelDetalleOrdenLayout.createSequentialGroup()
                                .addComponent(getDetalleOrdenDNI_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(getDetalleOrdenNombreCompleto_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                            .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 94, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(PanelDetalleOrdenLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(getBtnDetalleOrdenImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getTablaPrincipal.addTab("Detalle Orden", PanelDetalleOrden);

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder("Categoria"));

        getCategoriaID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getCategoriaID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getCategoriaID.setText("CAT00001");
        getCategoriaID.setToolTipText("");

        getCategoriaNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getCategoriaNombre.setForeground(new java.awt.Color(153, 153, 153));
        getCategoriaNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getCategoriaNombre.setText("NOMBRE");

        getBtnCategoriaAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/agregar_40pxls.png"))); // NOI18N
        getBtnCategoriaAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        getBtnCategoriaBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/equiz_40pxl.png"))); // NOI18N
        getBtnCategoriaBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        getBtnCategoriaModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/modificar_40pxls.png"))); // NOI18N
        getBtnCategoriaModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        getBtnCategoriaNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevo_40pxls.png"))); // NOI18N
        getBtnCategoriaNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(getCategoriaID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(getCategoriaNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(getBtnCategoriaAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(getBtnCategoriaBorrar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                        .addComponent(getBtnCategoriaNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(getBtnCategoriaModificar)))
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(getCategoriaID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(getCategoriaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(getBtnCategoriaAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(getBtnCategoriaBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(getBtnCategoriaModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(getBtnCategoriaNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );

        jScrollPane5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        getTablaCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(getTablaCategoria);

        javax.swing.GroupLayout PanelCategoriaLayout = new javax.swing.GroupLayout(PanelCategoria);
        PanelCategoria.setLayout(PanelCategoriaLayout);
        PanelCategoriaLayout.setHorizontalGroup(
            PanelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        PanelCategoriaLayout.setVerticalGroup(
            PanelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCategoriaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCategoriaLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getTablaPrincipal.addTab("Categorias", PanelCategoria);

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario"));

        getUsuarioNombreApellido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getUsuarioNombreApellido.setForeground(new java.awt.Color(153, 153, 153));
        getUsuarioNombreApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getUsuarioNombreApellido.setText("NOMBRE Y APELLIDO");

        getUsuarioCorreo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getUsuarioCorreo.setForeground(new java.awt.Color(153, 153, 153));
        getUsuarioCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getUsuarioCorreo.setText("CORREO");

        getUsuarioUsername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getUsuarioUsername.setForeground(new java.awt.Color(153, 153, 153));
        getUsuarioUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getUsuarioUsername.setText("USERNAME");

        getUsuarioPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getUsuarioPassword.setForeground(new java.awt.Color(153, 153, 153));
        getUsuarioPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getUsuarioPassword.setText("CONTRASEÑA");

        getBtnUsuarioAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/agregar_40pxls.png"))); // NOI18N
        getBtnUsuarioAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        getBtnUsuarioBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/equiz_40pxl.png"))); // NOI18N
        getBtnUsuarioBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        getBtnUsuarioNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevo_40pxls.png"))); // NOI18N
        getBtnUsuarioNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        getBtnUsuarioModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/modificar_40pxls.png"))); // NOI18N
        getBtnUsuarioModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        getUsuarioDNI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getUsuarioDNI.setForeground(new java.awt.Color(153, 153, 153));
        getUsuarioDNI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getUsuarioDNI.setText("DNI");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(getUsuarioNombreApellido)
                    .addComponent(getUsuarioCorreo)
                    .addComponent(getUsuarioUsername)
                    .addComponent(getUsuarioPassword)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(getBtnUsuarioNuevo)
                        .addGap(23, 23, 23)
                        .addComponent(getBtnUsuarioModificar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addComponent(getBtnUsuarioAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(getBtnUsuarioBorrar))
                    .addComponent(getUsuarioDNI))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(getUsuarioDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(getUsuarioNombreApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(getUsuarioCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(getUsuarioUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(getUsuarioPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(getBtnUsuarioBorrar)
                    .addComponent(getBtnUsuarioAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(getBtnUsuarioModificar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(getBtnUsuarioNuevo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jScrollPane6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        getTablaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(getTablaUsuario);

        javax.swing.GroupLayout PanelUsuarioLayout = new javax.swing.GroupLayout(PanelUsuario);
        PanelUsuario.setLayout(PanelUsuarioLayout);
        PanelUsuarioLayout.setHorizontalGroup(
            PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        PanelUsuarioLayout.setVerticalGroup(
            PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUsuarioLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getTablaPrincipal.addTab("Usuarios", PanelUsuario);

        jPanel11.add(getTablaPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 850, 530));

        jLabel1.setBackground(new java.awt.Color(255, 204, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logo_v2.jpg"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));

        getBtnOrden.setText("Orden");
        getBtnOrden.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        getBtnClientes.setText("Clientes");
        getBtnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        getBtnProductos.setText("Productos");
        getBtnProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        getBtnDetalleOrden.setText("Detalle Orden");
        getBtnDetalleOrden.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getBtnDetalleOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getBtnDetalleOrdenActionPerformed(evt);
            }
        });

        getBtnCategorias.setText("Categorias");
        getBtnCategorias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        getBtnUsuarios.setText("Usuarios");
        getBtnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        getBtnSalir.setText("Salir");
        getBtnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getBtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(getBtnOrden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(getBtnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(getBtnProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(getBtnDetalleOrden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(getBtnCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(getBtnUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(getBtnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(getBtnOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(getBtnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(getBtnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(getBtnDetalleOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(getBtnCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(getBtnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(getBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getBtnDetalleOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getBtnDetalleOrdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getBtnDetalleOrdenActionPerformed

    private void getBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getBtnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getBtnSalirActionPerformed

    private void getClienteCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getClienteCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getClienteCorreoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel IntroPanel;
    private javax.swing.JPanel PanelCategoria;
    private javax.swing.JPanel PanelCliente;
    private javax.swing.JPanel PanelDetalleOrden;
    private javax.swing.JPanel PanelOrden;
    private javax.swing.JPanel PanelProducto;
    private javax.swing.JPanel PanelUsuario;
    public javax.swing.JButton getBtnCategoriaAgregar;
    public javax.swing.JButton getBtnCategoriaBorrar;
    public javax.swing.JButton getBtnCategoriaModificar;
    public javax.swing.JButton getBtnCategoriaNuevo;
    public javax.swing.JButton getBtnCategorias;
    public javax.swing.JButton getBtnClienteAgregar;
    public javax.swing.JButton getBtnClienteBorrar;
    public javax.swing.JButton getBtnClienteModificar;
    public javax.swing.JButton getBtnClienteNuevo;
    public javax.swing.JButton getBtnClientes;
    public javax.swing.JButton getBtnDetalleOrden;
    public javax.swing.JButton getBtnDetalleOrdenIDOrden;
    public javax.swing.JButton getBtnDetalleOrdenImprimir;
    public javax.swing.JButton getBtnOrden;
    public javax.swing.JButton getBtnOrdenIDProducto;
    public javax.swing.JButton getBtnOrdenImprimir;
    public javax.swing.JButton getBtnOrdenNombreCliente;
    public javax.swing.JButton getBtnProductoAgregar;
    public javax.swing.JButton getBtnProductoBorrar;
    public javax.swing.JButton getBtnProductoModificar;
    public javax.swing.JButton getBtnProductoNuevo;
    public javax.swing.JButton getBtnProductos;
    public javax.swing.JButton getBtnSalir;
    public javax.swing.JButton getBtnUsuarioAgregar;
    public javax.swing.JButton getBtnUsuarioBorrar;
    public javax.swing.JButton getBtnUsuarioModificar;
    public javax.swing.JButton getBtnUsuarioNuevo;
    public javax.swing.JButton getBtnUsuarios;
    public javax.swing.JLabel getCategoriaID;
    public javax.swing.JTextField getCategoriaNombre;
    public javax.swing.JTextField getClienteCelular;
    public javax.swing.JTextField getClienteCorreo;
    public javax.swing.JTextField getClienteDNI;
    public javax.swing.JTextField getClienteDireccion;
    public javax.swing.JTextField getClienteNombreApellido;
    public javax.swing.JLabel getDNIUsuario;
    public javax.swing.JLabel getDetalleOrdenDNI_cliente;
    public javax.swing.JLabel getDetalleOrdenNombreCompleto_cliente;
    public javax.swing.JButton getOrdenAgregarPedido;
    public javax.swing.JSpinner getOrdenCantidad;
    public javax.swing.JLabel getOrdenDniCliente;
    public javax.swing.JLabel getOrdenNombreCliente;
    public javax.swing.JLabel getOrdenNombreProducto;
    public javax.swing.JLabel getOrdenPrecioProducto;
    public javax.swing.JLabel getOrdenProductoID;
    public javax.swing.JLabel getOrdenStockProducto;
    public javax.swing.JLabel getProductoID;
    public javax.swing.JComboBox<String> getProductoListaCategoria;
    public javax.swing.JTextField getProductoNombre;
    public javax.swing.JTextField getProductoPrecio;
    public javax.swing.JSpinner getProductoStock;
    public javax.swing.JTable getTablaCategoria;
    public javax.swing.JTable getTablaCliente;
    public javax.swing.JTable getTablaDetalleOrden;
    public javax.swing.JTable getTablaOrden;
    public javax.swing.JTabbedPane getTablaPrincipal;
    public javax.swing.JTable getTablaProducto;
    public javax.swing.JTable getTablaUsuario;
    public javax.swing.JTextField getUsuarioCorreo;
    public javax.swing.JTextField getUsuarioDNI;
    public javax.swing.JTextField getUsuarioNombreApellido;
    public javax.swing.JTextField getUsuarioPassword;
    public javax.swing.JTextField getUsuarioUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables
}
